#!/bin/bash

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}
need_config "${CONFIG}"

source_config

# Load the module associated with that device 
is_available ${REALDEVICE} || {
    if [ "$?" = "1" ]; then
        net_log $"$alias device ${DEVICE} does not seem to be present, delaying initialization." warning
        exit 1
    else
        exit 0
    fi
}

# Set baudrate. THIS IS MANDATORY
if [ -n "${BAUDRATE}" ]; then
    ip link set ${DEVICE} type can bitrate "${BAUDRATE}"
else
  net_log $"Device ${DEVICE} does not seem to have declared BOUDRATE (mandatory parameter) delaying initialization." warning
    exit 1
fi

# Set data baudrate. THIS IS MANDATORY when CAN FD capable is used
if [ -n "${DATA_BAUDRATE}" ]; then
    ip link set ${DEVICE} type can dbitrate "${DATA_BAUDRATE}"
else
  net_log $"Device ${DEVICE} does not seem to have declared DATA_BOUDRATE (mandatory parameter) delaying initialization." warning
    exit 1
fi

# Set restart time when interface gets to state bus-off. 
if [ -n "${RESTART_MS}" ]; then
    ip link set ${DEVICE} type can restart-ms "${RESTART_MS}"
fi

ip link set dev ${DEVICE} up

exit 0 
