.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "SYSCONFIG" "8" "April 2021" ""
.SH "NAME"
\fBsysconfig\fR \- Sysconfig related documentation
.SH "DESCRIPTION"
Doucumentation for /etc/sysconfig/* scripts
.SH "CONTENT"
.SH "GENERIC CONFIGURATION OPTIONS"
.SS "/etc/sysconfig/authconfig"
Used by authconfig to store information about the system\'s user information and authentication setup\. Changes made to this file have no effect until the next time authconfig is run\.
.TP
\fBUSEHESIOD\fR=\fIyes|no\fR
Whether or not the hesiod naming service is in use\. If not set, authconfig examines the passwd setting in \fB/etc/nsswitch\.conf\fR\.
.TP
\fBUSELDAP\fR=\fIyes|no\fR
Whether or not LDAP is used as a naming service\. If not set, authconfig examines the passwd setting in \fB/etc/nsswitch\.conf\fR\.
.TP
\fBUSENIS\fR=\fIyes|no\fR
Whether or not NIS is in use\. If not set, authconfig examines the passwd setting in \fB/etc/nsswitch\.conf\fR\.
.TP
\fBUSEKERBEROS\fR=\fIyes|no\fR
Whether or not Kerberos is in use\. If not set, authconfig examines the settings in \fB/etc/pam\.d/system\-auth\fR\.
.TP
\fBUSELDAPAUTH\fR=\fIyes|no\fR
Whether or not LDAP is being used for authentication\. If not set, authconfig examines the settings in \fB/etc/pam\.d/system\-auth\fR\. Note that this option is separate from \fBUSELDAP\fR, and that neither implies the other\.
.TP
\fBUSEMD5\fR=\fIyes|no\fR
Whether or not MD5\-based hashing should be used when setting passwords\. If not set, authconfig examines the settings in \fB/etc/pam\.d/system\-auth\fR\. This option affects authentication using both local files and LDAP\.
.TP
\fBUSESHADOW\fR=\fIyes|no\fR
Whether or not shadow passwords are in use\. If not set, authconfig checks for the existence of \fB/etc/shadow\fR\.
.TP
\fBUSESMBAUTH\fR=\fIyes|no\fR
Whether or not SMB authentication is in use\. If not set, authconfig examines the settings in \fB/etc/pam\.d/system\-auth\fR\.
.SS "/etc/sysconfig/autofsck"
Does not normally exist\. If it does, it can influence a choice whether or not to fsck after a crash\.
.TP
\fBAUTOFSCK_DEF_CHECK\fR=\fIyes|no\fR
If the user does not respond, choose whether or not to fsck\.
.TP
\fBAUTOFSCK_SINGLEUSER\fR=\fIyes|no\fR
If the user does not respond, choose whether or not to fsck\.
.SS "/etc/sysconfig/init"
.TP
\fBBOOTUP\fR=\fIbootup mode\fR
\fBBOOTUP=graphical\fR means use X Windows graphical boot up\. \fBBOOTUP=color\fR means colorized text mode boot display\. \fBBOOTUP=verbose\fR means old style display\. Anything else means simplified display, but without color or ANSI\-formatting
.TP
\fBLOGLEVEL\fR=\fInumber\fR
Sets the initial console logging level for the kernel\. The default is 7\. Number 8 means everything (including debugging)\. Number 1 means nothing except kernel panics\. Syslogd will override this once it starts\.
.TP
\fBRES_COL\fR=\fInumber\fR
Column of the screen to start status labels at\. Defaults to 60\.
.TP
\fBMOVE_TO_COL\fR=\fIcommand\fR
A command to move the cursor to \fB$RES_COL\fR\. Defaults to nasty\. ANSI sequences output by \fIecho \-e\fR\.
.TP
\fBSETCOLOR_SUCCESS\fR=\fIcommand\fR
A command to set the color to a color indicating success\. Defaults to nasty ANSI sequences output by \fIecho \-e\fR setting the color to green\.
.TP
\fBSETCOLOR_FAILURE\fR=\fIcommand\fR
A command to set the color to a color indicating failure\. Defaults to nasty ANSI sequences output by \fIecho \-e\fR setting the color to red\.
.TP
\fBSETCOLOR_WARNING\fR=\fIcommand\fR
A command to set the color to a color indicating warning\. Defaults to nasty ANSI sequences output by \fIecho \-e\fR setting the color to yellow\.
.TP
\fBSETCOLOR_NORMAL\fR=\fIcommand\fR
A command to set the color to \'normal\'\. Defaults to nasty ANSI sequences output by \fIecho \- e\fR\.
.TP
\fBPROMPT\fR=\fIyes|no\fR
Set to \fIyes\fR to enable the key check for interactive mode as well as asking if a filesystem check should be done\. Default is \fIno\fR and the kernel command line option \fIforcefsck\fR can be used to check the filesystems and \fIconfirm\fR can be used to enable interactive startup questions\.
.P
\fIobsoleted values from earlier releases\fR:
.TP
\fBMAGIC_SYSRQ\fR=\fIyes|no\fR
Setting this to \fIno\fR used to disable the magic sysrq key and \fBStop\-A\fR (break on serial console) on \fBSPARC\fR\. This setting has been moved into
.TP
\fBSTOP_A\fR=\fIyes|no\fR
Setting this to \fIno\fR used to disable the \fBStop\-A\fR (break on serial console) key on \fBSPARC\fR\. This setting has been moved into
.SH "Network\-scripts related documentation"
.SH "SYNOPSIS"
.SH "OPTIONS"
.SH "SYNTAX"
.SH "ENVIRONMENT"
.SH "RETURN VALUES"
.SH "STANDARDS"
.SH "SECURITY CONSIDERATIONS"
.SH "BUGS"
.SH "HISTORY"
.SH "AUTHOR"
.SH "COPYRIGHT"
.SH "SEE ALSO"

